### ISSUE TITLE
java.lang.IllegalArgumentException: character to be escaped is missing

### ISSUE THREAD

**Issue by tientm-it** [RyanSusana/elepy#58]
I have this problem when uploading files
OS: Windows 10

`java.lang.IllegalArgumentException: character to be escaped is missing
	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1020)
	at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:998)
	at com.elepy.uploads.DirectoryFileService.replaceNMatches(DirectoryFileService.java:35)
	at com.elepy.uploads.DirectoryFileService.decodeFileName(DirectoryFileService.java:105)
	at com.elepy.uploads.DirectoryFileService.uploadFile(DirectoryFileService.java:52)
	at com.elepy.uploads.FileUploadExtension.lambda$handleUpload$1(FileUploadExtension.java:58)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.elepy.uploads.FileUploadExtension.handleUpload(FileUploadExtension.java:62)
	at com.elepy.http.HttpService.lambda$addRoute$0(HttpService.java:38)
	at com.elepy.http.SparkService.lambda$igniteRoute$6(SparkService.java:132)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1672)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by RyanSusana** [comment]
Hi, thanks for the bug report!

Will work on it

**Comment by RyanSusana** [comment]
A potential fix will be released with 2.0.4.

That gets released today
